### ISSUE TITLE
Worker not showing in MPH

### ISSUE THREAD

**Issue by Dirt-Nasty** [kahiroka/ccminer-in-docker#2]
It looks like the miner is up and running according to the docker logs but I don't see the worker on my stats page.

Here is the parameter I have running to start the container

nvidia-docker run -d -e ALGO=lyra2v2 -e MINING_POOL=stratum+tcp://hub.miningpoolhub.com:17018 -e USER_NAME=worker.homelab -e PASSWORD=x -v /etc/localtime:/etc/localtime:ro ccminer/docker 

and attached is a sample of the docker log.
![image](https://user-images.githubusercontent.com/21373824/34359336-2a9d1f16-ea25-11e7-9f3e-3edbac8a555b.png)

**Comment by kahiroka** [comment]
Hi. I'm not a mining pool hub user, but could you check if the USER_NAME format is username.workername?

**Comment by Dirt-Nasty** [comment]
It is.  When I run ccminer on Windows here is what my command looks like:

ccminer.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u worker.homelab -p x -d 0

**Comment by Dirt-Nasty** [comment]
Anyway to contact you outside of Github?  Discord?

**Comment by kahiroka** [comment]
Which did you check your workers on 'Hub Workers' of the top page or 'Workers' of each coin's pool? As MPH spec (with tpruvot/ccminer at least), if you connect to algo switch mining pool you can see your workers on 'Hub Workers'. On the other hand, if you connect to simple coin mining pool you can see yours on 'Workers'. You should be able to see your results on 'Balances' of the top page in both cases.

**Comment by Dirt-Nasty** [comment]
I think their API just isn't updating properly.  So far this container has been rock solid man great work.  I'll close this as a non issue
