### ISSUE TITLE
Can't checkout cuda-9

### ISSUE THREAD

**Issue by mstraa** [kahiroka/ccminer-in-docker#3]
Hello !

First big thanks for your work !

I just tried to build the docker and it fail at "git checkout cuda-9".
I just removed this part and it seems to build fine.

On the docker I mine some Bytecoin at 177h/s against 300h/s on my machine (linux mint, 750ti).

For more convenience you can start the docker with a name : 

`nvidia-docker run -d \
      --name=ccminer \
      -e ALGO=<algorithm> \
      -e MINING_POOL=<MINING_POOL_WITH_PORT> \
      -e USER_NAME=<USERNAME/WORKERNAME> \
      -e PASSWORD=<PASSWORD> \
      -v /etc/localtime:/etc/localtime:ro \
      ccminer/docker `

And you can check the output of ccminer with : 

`docker logs -f ccminer`

**Comment by kahiroka** [comment]
Hi. Thanks for reporting. It seems that cuda-9 branch was merged into master and removed. I will fix it and improve the readme file.

**Comment by mstraa** [comment]
About the perf of ccminer, I built it on my OS and it's about the same perf as in the docker.
